### ISSUE TITLE
pytest-html does not pick up the test results when we run with pytest-parallel

### ISSUE THREAD

**Issue by GowriShankariSurendran** [browsertron/pytest-parallel#11]
We usually generate reports after every run for our tests using pytest-html.
But when we use pytest-parallel, we get 0 tests run in the report, but console correctly gives all details.
Can you please take a quick look and see if it is a problem with pytest-parallel?
I tried with xdist and that is able to collect the test correctly!

The sample command I use is 
py.test --workers 2 -m "ewlc" -sv com/tests/mock/e2e/eWLC_Client_Issues/blacklist_dhcp_eWLC_Issues_test.py -k test --config device_mock_Cluster.yaml --html=local-regression.html

**Comment by kevlened** [comment]
Looks like [`pytest_runtest_logreport`](https://github.com/pytest-dev/pytest-html/blob/8aa0671b97cf5e3d81d68d1d7848b1d1bd4cd83e/pytest_html/plugin.py#L500) isn't being called. I'll have to dig in

**Comment by kevlened** [comment]
Sorry, this one took a while. This should be resolved in [`0.0.9` on PyPI](https://pypi.org/project/pytest-parallel/0.0.9/).

As an aside, I'm trying to learn what most people are using `pytest` for and specifically `pytest-parallel`. Are you running integration tests, unit tests, something else?

**Comment by kevlened** [comment]
Thanks @GowriShankariSurendran for feedback, I'm glad the plugin was helpful!

I originally designed `pytest-parallel` to speed up integration tests, but to really take advantage of the speed, your tests' state must be pretty isolated. If you're having trouble with slow tests and unsure about the level of isolation your tests have, you might try using `--tests-per-worker` rather than the `--workers` option to see if your results improve. `--tests-per-worker` is more efficient than `--workers`, can be much faster, and may be more reliable in some cases.
